import localFont from "next/font/local";
<<<<<<< HEAD
import "./globals.css";
=======
>>>>>>> d5bfe75 (feat: Add themeprovider to the project.)
import theme from "./themes/theme";
import { ThemeProvider } from "@mui/material";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
<<<<<<< HEAD
      
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
=======
       <body>
>>>>>>> d5bfe75 (feat: Add themeprovider to the project.)
        <ThemeProvider theme={theme}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}

export default RootLayout