import theme from './themes/theme'
import { ThemeProvider } from '@mui/material'

// eslint-disable-next-line react-refresh/only-export-components
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}

export default RootLayout